// Package geo holds the world the globe draws: a land/sea mask and the places
// that can be searched for and aimed at.
//
// Both are generated by gen.go from Natural Earth's 1:110m vectors, which are
// in the public domain (https://www.naturalearthdata.com). The mask ships as
// a gzipped bitset of about 14 KiB and is expanded once, on first use, into
// 256 KiB of memory — which is what lets a lookup be a single indexed read
// with no allocation, on the draw path, for every pixel of every frame.
package geo

import (
	"bytes"
	"compress/gzip"
	_ "embed"
	"io"
	"math"
	"sync"
)

// Grid dimensions of the land mask, in cells of the equirectangular
// projection. Kept in step with gen.go.
const (
	maskW = 2048
	maskH = 1024
)

//go:embed land.bin.gz
var landGz []byte

var (
	landOnce sync.Once
	land     []byte
)

func loadLand() {
	zr, err := gzip.NewReader(bytes.NewReader(landGz))
	if err != nil {
		// The file is embedded from this package's own source tree; a failure
		// here means the build is corrupt, and an all-sea world makes that
		// obvious rather than crashing an application at startup.
		land = make([]byte, maskW*maskH/8)
		return
	}
	defer zr.Close()
	data, err := io.ReadAll(zr)
	if err != nil || len(data) != maskW*maskH/8 {
		land = make([]byte, maskW*maskH/8)
		return
	}
	land = data
}

// IsLand reports whether a point is on land. Latitude is degrees north,
// longitude degrees east; longitudes outside ±180 wrap, which is what lets a
// caller add a rotation without normalising first.
func IsLand(lat, lon float64) bool {
	landOnce.Do(loadLand)

	lon = math.Mod(lon+180, 360)
	if lon < 0 {
		lon += 360
	}
	x := int(lon * (maskW / 360.0))
	if x >= maskW {
		x = maskW - 1
	}

	y := int((90 - lat) * (maskH / 180.0))
	if y < 0 {
		y = 0
	} else if y >= maskH {
		y = maskH - 1
	}

	i := y*maskW + x
	return land[i/8]&(1<<uint(i%8)) != 0
}

//go:embed borders.bin.gz
var bordersGz []byte

// borderLevels is how many resolutions of the border mask are stored, each
// half the size of the one before. Kept in step with gen.go.
const borderLevels = 6

var (
	bordersOnce sync.Once
	borders     [borderLevels][]byte
)

func loadBorders() {
	zr, err := gzip.NewReader(bytes.NewReader(bordersGz))
	if err == nil {
		defer zr.Close()
		data, rerr := io.ReadAll(zr)
		if rerr == nil {
			at, w, h := 0, maskW, maskH
			for k := 0; k < borderLevels; k++ {
				n := w * h / 8
				if at+n > len(data) {
					break
				}
				borders[k] = data[at : at+n]
				at, w, h = at+n, w/2, h/2
			}
		}
	}
	// A build with no usable border data draws no borders rather than
	// failing: every level left nil reads as "no border here".
	for k := range borders {
		if borders[k] == nil {
			borders[k] = make([]byte, (maskW>>uint(k))*(maskH>>uint(k))/8)
		}
	}
}

// IsBorder reports whether a country boundary passes within one pixel of a
// point. degPerPixel is how much of the world that pixel covers, which
// decides which resolution to ask: a one-cell-wide line read at a coarse
// zoom would break into dots, so the mask is stored at six resolutions and
// the coarsest one whose cells still fit inside the pixel is used.
//
// Coasts are not borders here. Land meeting sea is already a change of
// colour, and drawing it again at low zoom buries the small countries.
func IsBorder(lat, lon, degPerPixel float64) bool {
	bordersOnce.Do(loadBorders)

	level := 0
	for k := borderLevels - 1; k > 0; k-- {
		if 360.0/float64(int(maskW)>>uint(k)) <= degPerPixel {
			level = k
			break
		}
	}
	w, h := maskW>>uint(level), maskH>>uint(level)

	lon = math.Mod(lon+180, 360)
	if lon < 0 {
		lon += 360
	}
	x := int(lon * (float64(w) / 360.0))
	if x >= w {
		x = w - 1
	}
	y := int((90 - lat) * (float64(h) / 180.0))
	if y < 0 {
		y = 0
	} else if y >= h {
		y = h - 1
	}

	i := y*w + x
	return borders[level][i/8]&(1<<uint(i%8)) != 0
}

// Kind distinguishes the two sorts of place in the table.
type Kind uint8

const (
	// Country is a country, centred on the point Natural Earth labels it at.
	Country Kind = iota
	// City is a capital or a large city.
	City
)

// String returns "country" or "city".
func (k Kind) String() string {
	if k == City {
		return "city"
	}
	return "country"
}

// Place is somewhere the globe can be aimed at.
type Place struct {
	// Name is the English name: "Turkey", "Istanbul".
	Name string
	// Local is a second name to search by, where it differs from Name: for a
	// country the name in its own language ("Türkiye" for Turkey), for a city
	// the plain ASCII spelling ("Izmir" for İzmir). It is searched but not
	// displayed; see Display.
	Local string
	// Code is the ISO 3166-1 alpha-2 code for a country, empty for a city.
	Code string
	// Region is the continent for a country, the country for a city.
	Region string
	// Lat and Lon are degrees north and east.
	Lat, Lon float64
	// Population is a city's, from Natural Earth's estimate. Zero for a country.
	Population int
	Kind       Kind
}

// Display returns the name to show, which is the English one. The local name
// is still searchable — typing "Türkiye" finds Turkey — it is simply not what
// the list and the map labels are written in, so that one map reads in one
// language rather than in a hundred.
func (p Place) Display() string { return p.Name }

var allOnce struct {
	sync.Once
	places []Place
}

// All returns every place, countries first. The slice is shared: it is read
// on the draw path and must not be modified.
func All() []Place {
	allOnce.Do(func() {
		out := make([]Place, 0, len(countries)+len(cities))
		out = append(out, countries...)
		out = append(out, cities...)
		allOnce.places = out
	})
	return allOnce.places
}
