// Package geo holds the world the globe draws: a land/sea mask and the places
// that can be searched for and aimed at.
//
// Both are generated by gen.go from Natural Earth's 1:110m vectors, which are
// in the public domain (https://www.naturalearthdata.com). The mask ships as
// a gzipped bitset of about 14 KiB and is expanded once, on first use, into
// 256 KiB of memory — which is what lets a lookup be a single indexed read
// with no allocation, on the draw path, for every pixel of every frame.
package geo

import (
	"bytes"
	"compress/gzip"
	_ "embed"
	"io"
	"math"
	"sync"
)

// Grid dimensions of the land mask, in cells of the equirectangular
// projection. Kept in step with gen.go.
const (
	maskW = 2048
	maskH = 1024
)

//go:embed land.bin.gz
var landGz []byte

var (
	landOnce sync.Once
	land     []byte
)

func loadLand() {
	zr, err := gzip.NewReader(bytes.NewReader(landGz))
	if err != nil {
		// The file is embedded from this package's own source tree; a failure
		// here means the build is corrupt, and an all-sea world makes that
		// obvious rather than crashing an application at startup.
		land = make([]byte, maskW*maskH/8)
		return
	}
	defer zr.Close()
	data, err := io.ReadAll(zr)
	if err != nil || len(data) != maskW*maskH/8 {
		land = make([]byte, maskW*maskH/8)
		return
	}
	land = data
}

// IsLand reports whether a point is on land. Latitude is degrees north,
// longitude degrees east; longitudes outside ±180 wrap, which is what lets a
// caller add a rotation without normalising first.
func IsLand(lat, lon float64) bool {
	landOnce.Do(loadLand)

	lon = math.Mod(lon+180, 360)
	if lon < 0 {
		lon += 360
	}
	x := int(lon * (maskW / 360.0))
	if x >= maskW {
		x = maskW - 1
	}

	y := int((90 - lat) * (maskH / 180.0))
	if y < 0 {
		y = 0
	} else if y >= maskH {
		y = maskH - 1
	}

	i := y*maskW + x
	return land[i/8]&(1<<uint(i%8)) != 0
}

// Kind distinguishes the two sorts of place in the table.
type Kind uint8

const (
	// Country is a country, centred on the point Natural Earth labels it at.
	Country Kind = iota
	// City is a capital or a large city.
	City
)

// String returns "country" or "city".
func (k Kind) String() string {
	if k == City {
		return "city"
	}
	return "country"
}

// Place is somewhere the globe can be aimed at.
type Place struct {
	// Name is the English name: "Turkey", "Istanbul".
	Name string
	// Local is the name in the country's own language where Natural Earth
	// records one and it differs from Name: "Türkiye" for Turkey. It is
	// searched but not displayed; see Display.
	Local string
	// Code is the ISO 3166-1 alpha-2 code for a country, empty for a city.
	Code string
	// Region is the continent for a country, the country for a city.
	Region string
	// Lat and Lon are degrees north and east.
	Lat, Lon float64
	// Population is a city's, from Natural Earth's estimate. Zero for a country.
	Population int
	Kind       Kind
}

// Display returns the name to show, which is the English one. The local name
// is still searchable — typing "Türkiye" finds Turkey — it is simply not what
// the list and the map labels are written in, so that one map reads in one
// language rather than in a hundred.
func (p Place) Display() string { return p.Name }

var allOnce struct {
	sync.Once
	places []Place
}

// All returns every place, countries first. The slice is shared: it is read
// on the draw path and must not be modified.
func All() []Place {
	allOnce.Do(func() {
		out := make([]Place, 0, len(countries)+len(cities))
		out = append(out, countries...)
		out = append(out, cities...)
		allOnce.places = out
	})
	return allOnce.places
}
